[package]
name = "rmv"
version = "0.0.3"
edition = "2024"
author = "mikku"

[[bin]]
name = "rmv"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
indicatif = "0.18.0"
rand = "0.9.2"
walkdir = "2.5.0"
